### ISSUE TITLE
Cant send body buffer from asn.1 data

### ISSUE THREAD

**Issue by Recback777** [nktnet1/sync-request-curl#116]
```js
var fs = require('fs');
var buf = fs.readFileSync('./tspsig.dmp');

var head = {'Content-Type':'application/timestamp-query'};
var request = require('sync-request-curl');

var res = request(
    'POST',
    'localhost:3000',
    {
        headers: {'Content-Type': 'application/timestamp-query'},
        body: buf
    }
);

```
     
[tspsig.dmp](https://github.com/nktnet1/sync-request-curl/files/14157169/tspsig.dmp)

content-length from tspsig.dmp’s buffer is 165, but when sending data is received on server side, data from body becomes incorrect and content-length incorrect too.

I tried another libraries such as require('request'), had correct data from body, but these libraries dont work sync and with proxy at the same time.

**Comment by nktnet1** [comment]
Hi @Recback777 ,

Thank you for reporting the bug.

I've made a patch to fix it (v2.1.11) - can you try updating sync-request-curl with
```
npm i sync-request-curl@latest
```
and see if the issue is still present?

**Comment by Recback777** [comment]
Hello! I just tried a real test with real addresses, and I received code 400 with  "sync-request-curl" and code 200 with "request". Example:

var fs = require('fs');
        var buf = (fs.readFileSync('./tspsig')); 
    
//code 400
//TEST1==================================
  var request = require('sync-request-curl');
  var req = request(
      'POST',
     'http://acsk.privatbank.ua/services/tsp/',
     {
        headers:{'Content-Type':'application/timestamp-query'},
        body:buf
      }
     );

  var res = req;


//code 200
//TEST2==================================
  var request = require('request')

  var options = {
    headers: {'Content-Type':'application/timestamp-query'},
    url: 'http://acsk.privatbank.ua/services/tsp/',
    body: buf,
    method: 'POST',
    encoding: null,
  }
  return new Promise(function(resolve, reject) {
   request(options,
    function (error, response, body) {
      if (!error && response.statusCode == 200) {
        resolve(body)
      } else {
        if (error != null){
          reject(error)
        }
        if(response != null){
          if(response.statusCode != 200) {
            reject(response.statusCode)
          }
        }
    }
})

})

**Comment by nktnet1** [comment]
@Recback777  I added support for sending buffers in chunks in version 2.2.0. 
Let me know if there are any other issues :).

**Comment by Recback777** [comment]
Hello @nktnet1 

It works!
Thanks!😊 Good job!🤝
